apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-app
  namespace: default
  labels:
    app: jwt-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jwt-app
  template:
    metadata:
      labels:
        app: jwt-app
    spec:
      containers:
        - name: jwt-app
          image: 102205/jwt-app:1.3
          ports:
            - containerPort: 3000
        - name: mongo-connect
          image: mongo
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: jwt-app-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: jwt-app
  ports:
    - port: 8080
      targetPort: 3000
      nodePort: 31515
