version: '3'
services:
  app:
    image: 102205/jwt-app:1.2
    container_name: jwt-app
    restart: unless-stopped
    # build: .
    ports:
      - '8080:3000'
    volumes:
      - .:/www/sites
      - /www/sites/node_modules
    links:
      - db
    depends_on:
      - db
  db:
    image: mongo
    container_name: mongo-connect
    restart: unless-stopped
    ports:
      - '27018:27017'
